sudo: required

language: cpp

git:
    depth: 3

branches:
only:
  - master

os: osx
osx_image: xcode8
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
compiler: clang
before_install:
  - brew update
  - brew install eigen
  - mkdir build
  - mkdir build/darwin
install:
  - cd build/darwin
  - cmake ../..
script:
  - make -j`nproc` all
